version: '3'

services:
  postgres:
    restart: on-failure
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  your-go-service:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
